### ISSUE TITLE
训练到第51次无法继续

### ISSUE THREAD

**Issue by TTgogogo** [OmniXRI/OpenVINO_RealSense_HarvestBot#2]
你好！我使用my_train.py进行模型训练，但训练到第二阶段，即epoch 51时，无法继续。请问是什么原因？是硬件性能不足吗？

**Comment by OmniXRI** [comment]
我很難判定你的問題出在那？
最近我有寫了另一個範例，更方便實現，可直接在Google Colab上實現，可參考下方連結。
https://github.com/OmniXRI/Yolov4-tiny_Colab_User_Datasets
